indata = open("input.txt", 'r+')
print('Vị trí con trỏ',indata.tell())
print('print lần 1=\t',indata.read(2))
print('print lần 2=\t',indata.read(3))
indata.seek(0,1)
print('Vị trí con trỏ',indata.tell())
indata.write("saigon")
print('print lần 3=\t',indata.read())
indata.close()
print('print lần 4=\t',open("input.txt").read())